#include<stdint.h>

#define porta_pin (volatile uint8_t *)0x20
#define porta_dir (volatile uint8_t *)0x2
#define porta_dat (volatile uint8_t *)0x22
#define portb_pin (volatile uint8_t *)0x23
#define portb_dir (volatile uint8_t *)0x24
#define portb_dat (volatile uint8_t *)0x25
#define portc_pin (volatile uint8_t *)0x26
#define portc_dir (volatile uint8_t *)0x27
#define portc_dat (volatile uint8_t *)0x28
#define portd_pin (volatile uint8_t *)0x29
#define portd_dir (volatile uint8_t *)0x2a
#define portd_dat (volatile uint8_t *)0x2b
#define porte_pin (volatile uint8_t *)0x2c
#define porte_dir (volatile uint8_t *)0x2d
#define porte_dat (volatile uint8_t *)0x2e
#define portf_pin (volatile uint8_t *)0x2f
#define portf_dir (volatile uint8_t *)0x30
#define portf_dat (volatile uint8_t *)0x31
#define portg_pin (volatile uint8_t *)0x32
#define portg_dir (volatile uint8_t *)0x33
#define portg_dat (volatile uint8_t *)0x34
#define porth_pin (volatile uint8_t *)0x100
#define porth_dir (volatile uint8_t *)0x101
#define porth_dat (volatile uint8_t *)0x102
#define portj_pin (volatile uint8_t *)0x103
#define portj_dir (volatile uint8_t *)0x104
#define portj_dat (volatile uint8_t *)0x105
#define portk_pin (volatile uint8_t *)0x106
#define portk_dir (volatile uint8_t *)0x107
#define portk_dat (volatile uint8_t *)0x108
#define portl_pin (volatile uint8_t *)0x109
#define portl_dir (volatile uint8_t *)0x10a
#define portl_dat (volatile uint8_t *)0x10b